/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package crisp.pdfmaker

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test fun testPass() {
        assertEquals(1,1)
    }
}
